### ISSUE TITLE
pythoncom.PumpWaitingMessages not working

### ISSUE THREAD

**Issue by perak96** [Skarzee/KeystrokeDynamics#2]
Hello,

I am trying to run this code and I have a problem that my program is stuck in the main loop. No keystrokes are recorded and when I press ESC button - it does not end the main loop. Do you have any solution to this.. my guess is that something is not fine with the function pythoncom.PumpWaitingMessages().

Thanks in advance.

**Comment by triwats** [comment]
Hi @perak96 - Is this still relevant to you? Sorry for the delay I wish I could say I was also making furniture but that's not the case. I currently DO have access to a windows machine so I can look at this, but my feeling is that perhaps the dependnacies have changed.

**Comment by perak96** [comment]
Hello, it is not relevant anymore for me. Thanks for the answer anyway.

**Comment by triwats** [comment]
@perak96 - thanks for getting back to me. Closing this.
